swagger: '2.0'
info:
  title: TSHub API
  description: The REST API for the TimeSeries-Profiler
  version: "0.1"
  contact:
    name: post@c-ha.de
host: localhost:8080
schemes:
  - http
basePath: /v0.1
produces:
  - application/json
paths:

  /hosts:
    get:
      summary: Get a list of available physical hosts
      operationId: getHosts
      responses:
        200:
          description: An array of hosts
          schema:
            type: array
            items:
              $ref: "#/definitions/Host"
        500:  
          description: Internal Server Error

  /host/{hostname}:
    get:
      summary: Get details of the given host
      operationId: getHost
      parameters:
        - in: path
          name: hostname
          required: true
          type: string      
      responses:
        200:
          description: Host details
          schema:
            $ref: "#/definitions/HostDetails"
        404:
          description: Element not found            
        500:  
          description: Internal Server Error

  /host/{hostname}/plotdata:
    get:
      summary: Returns the plotdata (past and prediction) of given host and metric
      operationId: getHostPlotdata
      parameters:
        - in: path
          name: hostname
          required: true
          type: string
        - name: metric
          in: query
          required: true
          type: string
        - name: timeframe
          in: query
          required: false
          type: string
      responses:
        200:
          description: plotdata for given host and metric
          schema:
            $ref: "#/definitions/PlotData"
        404:
          description: Element not found            
        500:  
          description: Internal Server Error

  /domains:
    get:
      summary: Get a list of available domains (virtual machines / containers)
      operationId: getDomains
      parameters:
        - name: hostname
          in: query
          required: false
          type: string
      responses:
        200:
          description: An array of domains
          schema:
            type: array
            items:
              $ref: "#/definitions/Domain"
        500:  
          description: Internal Server Error

  /domain/{domainname}:
    get:
      summary: Get details of given domain by its name
      operationId: getDomain
      parameters:
        - in: path
          name: domainname
          required: true
          type: string
      responses:
        200:
          description: An array of domains
          schema:
            $ref: "#/definitions/DomainDetails"
        404:
          description: Element not found            
        500:  
          description: Internal Server Error

  /domain/{domainname}/plotdata:
    get:
      summary: Returns the plotdata (past and prediction) of given domain and metric
      operationId: getDomainPlotdata
      parameters:
        - in: path
          name: domainname
          required: true
          type: string
        - name: metric
          in: query
          required: true
          type: string
        - name: timeframe
          in: query
          required: false
          type: string
      responses:
        200:
          description: plotdata for given domain and metric
          schema:
            $ref: "#/definitions/PlotData"
        404:
          description: Element not found            
        500:  
          description: Internal Server Error

  /profiles:
    get:
      summary: Get a list of names from stored profiles
      operationId: getProfileNames
      responses:
        200:
          description: An array profile names
          schema:
            type: array
            items:
              type: string
        404:
          description: Element not found
        500:  
          description: Internal Server Error
     
  /profile/{profilename}:
    get:
      summary: Get the full profile by given name
      operationId: getProfile
      parameters:
        - in: path
          name: profilename
          required: true
          type: string   
      responses:
        200:
          description: successful operation
          schema:
            $ref: "#/definitions/AnyValue"
        404:
          description: Element not found
        500:  
          description: Internal Server Error  

definitions:
  AnyValue: {}  

  Host:
    type: object
    properties:
      name:
        type: string
      cores:
        type: integer
      ram:
        type: integer
      instancecount:
        type: integer

  HostDetails:
    type: object
    properties:
      name:
        type: string
      overbooking:
        type: object
        properties:
          cpuCores:
            type: integer
          cpuUtil:
            type: integer
          ram:
            type: integer
          diskIO:
            type: integer
          netIO:
            type: integer

  Domain:
    type: object
    properties:
      name:
        type: string
      cores:
        type: integer
      ram:
        type: integer

  DomainDetails:
    type: object
    properties:
      name:
        type: string
      cores:
        type: integer
      ram:
        type: integer    

  PlotData:
    type: object
    properties:
      metric:
        type: string
      past:
        type: array
        items:
          $ref: "#/definitions/PlotDataItem"
      future:
        type: array
        items:
          $ref: "#/definitions/PlotDataItem"

  PlotDataItem:
    type: object
    properties:
      timestamp:
        type: integer
      value:
        type: number