// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetHostsHandlerFunc turns a function with the right signature into a get hosts handler
type GetHostsHandlerFunc func(GetHostsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetHostsHandlerFunc) Handle(params GetHostsParams) middleware.Responder {
	return fn(params)
}

// GetHostsHandler interface for that can handle valid get hosts params
type GetHostsHandler interface {
	Handle(GetHostsParams) middleware.Responder
}

// NewGetHosts creates a new http.Handler for the get hosts operation
func NewGetHosts(ctx *middleware.Context, handler GetHostsHandler) *GetHosts {
	return &GetHosts{Context: ctx, Handler: handler}
}

/*GetHosts swagger:route GET /hosts getHosts

Get a list of available physical hosts

*/
type GetHosts struct {
	Context *middleware.Context
	Handler GetHostsHandler
}

func (o *GetHosts) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetHostsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
