// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/cha87de/tshub/models"
)

// GetDomainPlotdataOKCode is the HTTP code returned for type GetDomainPlotdataOK
const GetDomainPlotdataOKCode int = 200

/*GetDomainPlotdataOK plotdata for given domain and metric

swagger:response getDomainPlotdataOK
*/
type GetDomainPlotdataOK struct {

	/*
	  In: Body
	*/
	Payload *models.PlotData `json:"body,omitempty"`
}

// NewGetDomainPlotdataOK creates GetDomainPlotdataOK with default headers values
func NewGetDomainPlotdataOK() *GetDomainPlotdataOK {

	return &GetDomainPlotdataOK{}
}

// WithPayload adds the payload to the get domain plotdata o k response
func (o *GetDomainPlotdataOK) WithPayload(payload *models.PlotData) *GetDomainPlotdataOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get domain plotdata o k response
func (o *GetDomainPlotdataOK) SetPayload(payload *models.PlotData) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDomainPlotdataOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDomainPlotdataNotFoundCode is the HTTP code returned for type GetDomainPlotdataNotFound
const GetDomainPlotdataNotFoundCode int = 404

/*GetDomainPlotdataNotFound Element not found

swagger:response getDomainPlotdataNotFound
*/
type GetDomainPlotdataNotFound struct {
}

// NewGetDomainPlotdataNotFound creates GetDomainPlotdataNotFound with default headers values
func NewGetDomainPlotdataNotFound() *GetDomainPlotdataNotFound {

	return &GetDomainPlotdataNotFound{}
}

// WriteResponse to the client
func (o *GetDomainPlotdataNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetDomainPlotdataInternalServerErrorCode is the HTTP code returned for type GetDomainPlotdataInternalServerError
const GetDomainPlotdataInternalServerErrorCode int = 500

/*GetDomainPlotdataInternalServerError Internal Server Error

swagger:response getDomainPlotdataInternalServerError
*/
type GetDomainPlotdataInternalServerError struct {
}

// NewGetDomainPlotdataInternalServerError creates GetDomainPlotdataInternalServerError with default headers values
func NewGetDomainPlotdataInternalServerError() *GetDomainPlotdataInternalServerError {

	return &GetDomainPlotdataInternalServerError{}
}

// WriteResponse to the client
func (o *GetDomainPlotdataInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
