// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/cha87de/tshub/models"
)

// GetHostsOKCode is the HTTP code returned for type GetHostsOK
const GetHostsOKCode int = 200

/*GetHostsOK An array of hosts

swagger:response getHostsOK
*/
type GetHostsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Host `json:"body,omitempty"`
}

// NewGetHostsOK creates GetHostsOK with default headers values
func NewGetHostsOK() *GetHostsOK {

	return &GetHostsOK{}
}

// WithPayload adds the payload to the get hosts o k response
func (o *GetHostsOK) WithPayload(payload []*models.Host) *GetHostsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get hosts o k response
func (o *GetHostsOK) SetPayload(payload []*models.Host) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHostsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Host, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetHostsInternalServerErrorCode is the HTTP code returned for type GetHostsInternalServerError
const GetHostsInternalServerErrorCode int = 500

/*GetHostsInternalServerError Internal Server Error

swagger:response getHostsInternalServerError
*/
type GetHostsInternalServerError struct {
}

// NewGetHostsInternalServerError creates GetHostsInternalServerError with default headers values
func NewGetHostsInternalServerError() *GetHostsInternalServerError {

	return &GetHostsInternalServerError{}
}

// WriteResponse to the client
func (o *GetHostsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
