// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetDomainsHandlerFunc turns a function with the right signature into a get domains handler
type GetDomainsHandlerFunc func(GetDomainsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDomainsHandlerFunc) Handle(params GetDomainsParams) middleware.Responder {
	return fn(params)
}

// GetDomainsHandler interface for that can handle valid get domains params
type GetDomainsHandler interface {
	Handle(GetDomainsParams) middleware.Responder
}

// NewGetDomains creates a new http.Handler for the get domains operation
func NewGetDomains(ctx *middleware.Context, handler GetDomainsHandler) *GetDomains {
	return &GetDomains{Context: ctx, Handler: handler}
}

/*GetDomains swagger:route GET /domains getDomains

Get a list of available domains (virtual machines / containers)

*/
type GetDomains struct {
	Context *middleware.Context
	Handler GetDomainsHandler
}

func (o *GetDomains) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetDomainsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
