// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDomainPlotdataParams creates a new GetDomainPlotdataParams object
// no default values defined in spec.
func NewGetDomainPlotdataParams() GetDomainPlotdataParams {

	return GetDomainPlotdataParams{}
}

// GetDomainPlotdataParams contains all the bound params for the get domain plotdata operation
// typically these are obtained from a http.Request
//
// swagger:parameters getDomainPlotdata
type GetDomainPlotdataParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	Domainname string
	/*
	  Required: true
	  In: query
	*/
	Metric string
	/*
	  In: query
	*/
	Timeframe *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetDomainPlotdataParams() beforehand.
func (o *GetDomainPlotdataParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	rDomainname, rhkDomainname, _ := route.Params.GetOK("domainname")
	if err := o.bindDomainname(rDomainname, rhkDomainname, route.Formats); err != nil {
		res = append(res, err)
	}

	qMetric, qhkMetric, _ := qs.GetOK("metric")
	if err := o.bindMetric(qMetric, qhkMetric, route.Formats); err != nil {
		res = append(res, err)
	}

	qTimeframe, qhkTimeframe, _ := qs.GetOK("timeframe")
	if err := o.bindTimeframe(qTimeframe, qhkTimeframe, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindDomainname binds and validates parameter Domainname from path.
func (o *GetDomainPlotdataParams) bindDomainname(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Domainname = raw

	return nil
}

// bindMetric binds and validates parameter Metric from query.
func (o *GetDomainPlotdataParams) bindMetric(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("metric", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false
	if err := validate.RequiredString("metric", "query", raw); err != nil {
		return err
	}

	o.Metric = raw

	return nil
}

// bindTimeframe binds and validates parameter Timeframe from query.
func (o *GetDomainPlotdataParams) bindTimeframe(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Timeframe = &raw

	return nil
}
