// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetDomainHandlerFunc turns a function with the right signature into a get domain handler
type GetDomainHandlerFunc func(GetDomainParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDomainHandlerFunc) Handle(params GetDomainParams) middleware.Responder {
	return fn(params)
}

// GetDomainHandler interface for that can handle valid get domain params
type GetDomainHandler interface {
	Handle(GetDomainParams) middleware.Responder
}

// NewGetDomain creates a new http.Handler for the get domain operation
func NewGetDomain(ctx *middleware.Context, handler GetDomainHandler) *GetDomain {
	return &GetDomain{Context: ctx, Handler: handler}
}

/*GetDomain swagger:route GET /domain/{domainname} getDomain

Get details of given domain by its name

*/
type GetDomain struct {
	Context *middleware.Context
	Handler GetDomainHandler
}

func (o *GetDomain) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetDomainParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
