// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/cha87de/tshub/models"
)

// GetDomainsOKCode is the HTTP code returned for type GetDomainsOK
const GetDomainsOKCode int = 200

/*GetDomainsOK An array of domains

swagger:response getDomainsOK
*/
type GetDomainsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Domain `json:"body,omitempty"`
}

// NewGetDomainsOK creates GetDomainsOK with default headers values
func NewGetDomainsOK() *GetDomainsOK {

	return &GetDomainsOK{}
}

// WithPayload adds the payload to the get domains o k response
func (o *GetDomainsOK) WithPayload(payload []*models.Domain) *GetDomainsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get domains o k response
func (o *GetDomainsOK) SetPayload(payload []*models.Domain) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDomainsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Domain, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetDomainsInternalServerErrorCode is the HTTP code returned for type GetDomainsInternalServerError
const GetDomainsInternalServerErrorCode int = 500

/*GetDomainsInternalServerError Internal Server Error

swagger:response getDomainsInternalServerError
*/
type GetDomainsInternalServerError struct {
}

// NewGetDomainsInternalServerError creates GetDomainsInternalServerError with default headers values
func NewGetDomainsInternalServerError() *GetDomainsInternalServerError {

	return &GetDomainsInternalServerError{}
}

// WriteResponse to the client
func (o *GetDomainsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
