// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDomainParams creates a new GetDomainParams object
// no default values defined in spec.
func NewGetDomainParams() GetDomainParams {

	return GetDomainParams{}
}

// GetDomainParams contains all the bound params for the get domain operation
// typically these are obtained from a http.Request
//
// swagger:parameters getDomain
type GetDomainParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	Domainname string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetDomainParams() beforehand.
func (o *GetDomainParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rDomainname, rhkDomainname, _ := route.Params.GetOK("domainname")
	if err := o.bindDomainname(rDomainname, rhkDomainname, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindDomainname binds and validates parameter Domainname from path.
func (o *GetDomainParams) bindDomainname(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Domainname = raw

	return nil
}
