// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetProfileNamesHandlerFunc turns a function with the right signature into a get profile names handler
type GetProfileNamesHandlerFunc func(GetProfileNamesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetProfileNamesHandlerFunc) Handle(params GetProfileNamesParams) middleware.Responder {
	return fn(params)
}

// GetProfileNamesHandler interface for that can handle valid get profile names params
type GetProfileNamesHandler interface {
	Handle(GetProfileNamesParams) middleware.Responder
}

// NewGetProfileNames creates a new http.Handler for the get profile names operation
func NewGetProfileNames(ctx *middleware.Context, handler GetProfileNamesHandler) *GetProfileNames {
	return &GetProfileNames{Context: ctx, Handler: handler}
}

/*GetProfileNames swagger:route GET /profiles getProfileNames

Get a list of names from stored profiles

*/
type GetProfileNames struct {
	Context *middleware.Context
	Handler GetProfileNamesHandler
}

func (o *GetProfileNames) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetProfileNamesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
