// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/cha87de/tshub/models"
)

// GetHostPlotdataOKCode is the HTTP code returned for type GetHostPlotdataOK
const GetHostPlotdataOKCode int = 200

/*GetHostPlotdataOK plotdata for given host and metric

swagger:response getHostPlotdataOK
*/
type GetHostPlotdataOK struct {

	/*
	  In: Body
	*/
	Payload *models.PlotData `json:"body,omitempty"`
}

// NewGetHostPlotdataOK creates GetHostPlotdataOK with default headers values
func NewGetHostPlotdataOK() *GetHostPlotdataOK {

	return &GetHostPlotdataOK{}
}

// WithPayload adds the payload to the get host plotdata o k response
func (o *GetHostPlotdataOK) WithPayload(payload *models.PlotData) *GetHostPlotdataOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get host plotdata o k response
func (o *GetHostPlotdataOK) SetPayload(payload *models.PlotData) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHostPlotdataOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetHostPlotdataNotFoundCode is the HTTP code returned for type GetHostPlotdataNotFound
const GetHostPlotdataNotFoundCode int = 404

/*GetHostPlotdataNotFound Element not found

swagger:response getHostPlotdataNotFound
*/
type GetHostPlotdataNotFound struct {
}

// NewGetHostPlotdataNotFound creates GetHostPlotdataNotFound with default headers values
func NewGetHostPlotdataNotFound() *GetHostPlotdataNotFound {

	return &GetHostPlotdataNotFound{}
}

// WriteResponse to the client
func (o *GetHostPlotdataNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetHostPlotdataInternalServerErrorCode is the HTTP code returned for type GetHostPlotdataInternalServerError
const GetHostPlotdataInternalServerErrorCode int = 500

/*GetHostPlotdataInternalServerError Internal Server Error

swagger:response getHostPlotdataInternalServerError
*/
type GetHostPlotdataInternalServerError struct {
}

// NewGetHostPlotdataInternalServerError creates GetHostPlotdataInternalServerError with default headers values
func NewGetHostPlotdataInternalServerError() *GetHostPlotdataInternalServerError {

	return &GetHostPlotdataInternalServerError{}
}

// WriteResponse to the client
func (o *GetHostPlotdataInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
