// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetHostPlotdataParams creates a new GetHostPlotdataParams object
// no default values defined in spec.
func NewGetHostPlotdataParams() GetHostPlotdataParams {

	return GetHostPlotdataParams{}
}

// GetHostPlotdataParams contains all the bound params for the get host plotdata operation
// typically these are obtained from a http.Request
//
// swagger:parameters getHostPlotdata
type GetHostPlotdataParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	Hostname string
	/*
	  Required: true
	  In: query
	*/
	Metric string
	/*
	  In: query
	*/
	Timeframe *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetHostPlotdataParams() beforehand.
func (o *GetHostPlotdataParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	rHostname, rhkHostname, _ := route.Params.GetOK("hostname")
	if err := o.bindHostname(rHostname, rhkHostname, route.Formats); err != nil {
		res = append(res, err)
	}

	qMetric, qhkMetric, _ := qs.GetOK("metric")
	if err := o.bindMetric(qMetric, qhkMetric, route.Formats); err != nil {
		res = append(res, err)
	}

	qTimeframe, qhkTimeframe, _ := qs.GetOK("timeframe")
	if err := o.bindTimeframe(qTimeframe, qhkTimeframe, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindHostname binds and validates parameter Hostname from path.
func (o *GetHostPlotdataParams) bindHostname(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Hostname = raw

	return nil
}

// bindMetric binds and validates parameter Metric from query.
func (o *GetHostPlotdataParams) bindMetric(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("metric", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false
	if err := validate.RequiredString("metric", "query", raw); err != nil {
		return err
	}

	o.Metric = raw

	return nil
}

// bindTimeframe binds and validates parameter Timeframe from query.
func (o *GetHostPlotdataParams) bindTimeframe(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Timeframe = &raw

	return nil
}
