// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetDomainPlotdataHandlerFunc turns a function with the right signature into a get domain plotdata handler
type GetDomainPlotdataHandlerFunc func(GetDomainPlotdataParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDomainPlotdataHandlerFunc) Handle(params GetDomainPlotdataParams) middleware.Responder {
	return fn(params)
}

// GetDomainPlotdataHandler interface for that can handle valid get domain plotdata params
type GetDomainPlotdataHandler interface {
	Handle(GetDomainPlotdataParams) middleware.Responder
}

// NewGetDomainPlotdata creates a new http.Handler for the get domain plotdata operation
func NewGetDomainPlotdata(ctx *middleware.Context, handler GetDomainPlotdataHandler) *GetDomainPlotdata {
	return &GetDomainPlotdata{Context: ctx, Handler: handler}
}

/*GetDomainPlotdata swagger:route GET /domain/{domainname}/plotdata getDomainPlotdata

Returns the plotdata (past and prediction) of given domain and metric

*/
type GetDomainPlotdata struct {
	Context *middleware.Context
	Handler GetDomainPlotdataHandler
}

func (o *GetDomainPlotdata) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetDomainPlotdataParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
