// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi TSHub API
The REST API for the TimeSeries-Profiler


    Schemes:
      http
    Host: localhost:8080
    BasePath: /v0.1
    Version: 0.1
    Contact: post@c-ha.de

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
