// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "The REST API for the TimeSeries-Profiler",
    "title": "TSHub API",
    "contact": {
      "name": "post@c-ha.de"
    },
    "version": "0.1"
  },
  "host": "localhost:8080",
  "basePath": "/v0.1",
  "paths": {
    "/profile/{profilename}": {
      "get": {
        "summary": "Get the full profile by given name",
        "operationId": "getProfile",
        "parameters": [
          {
            "type": "string",
            "name": "profilename",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/AnyValue"
            }
          },
          "404": {
            "description": "Element not found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/profiles": {
      "get": {
        "summary": "Get a list of names from stored profiles",
        "operationId": "getProfileNames",
        "responses": {
          "200": {
            "description": "An array profile names",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "404": {
            "description": "Element not found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    }
  },
  "definitions": {
    "AnyValue": {}
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "The REST API for the TimeSeries-Profiler",
    "title": "TSHub API",
    "contact": {
      "name": "post@c-ha.de"
    },
    "version": "0.1"
  },
  "host": "localhost:8080",
  "basePath": "/v0.1",
  "paths": {
    "/profile/{profilename}": {
      "get": {
        "summary": "Get the full profile by given name",
        "operationId": "getProfile",
        "parameters": [
          {
            "type": "string",
            "name": "profilename",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/AnyValue"
            }
          },
          "404": {
            "description": "Element not found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/profiles": {
      "get": {
        "summary": "Get a list of names from stored profiles",
        "operationId": "getProfileNames",
        "responses": {
          "200": {
            "description": "An array profile names",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "404": {
            "description": "Element not found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    }
  },
  "definitions": {
    "AnyValue": {}
  }
}`))
}
