// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// PlotDataItem plot data item
// swagger:model PlotDataItem
type PlotDataItem struct {

	// timestamp
	Timestamp int64 `json:"timestamp,omitempty"`

	// value
	Value float64 `json:"value,omitempty"`
}

// Validate validates this plot data item
func (m *PlotDataItem) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PlotDataItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PlotDataItem) UnmarshalBinary(b []byte) error {
	var res PlotDataItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
