// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PlotData plot data
// swagger:model PlotData
type PlotData struct {

	// future
	Future []*PlotDataItem `json:"future"`

	// metric
	Metric string `json:"metric,omitempty"`

	// past
	Past []*PlotDataItem `json:"past"`
}

// Validate validates this plot data
func (m *PlotData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFuture(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePast(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PlotData) validateFuture(formats strfmt.Registry) error {

	if swag.IsZero(m.Future) { // not required
		return nil
	}

	for i := 0; i < len(m.Future); i++ {
		if swag.IsZero(m.Future[i]) { // not required
			continue
		}

		if m.Future[i] != nil {
			if err := m.Future[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("future" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *PlotData) validatePast(formats strfmt.Registry) error {

	if swag.IsZero(m.Past) { // not required
		return nil
	}

	for i := 0; i < len(m.Past); i++ {
		if swag.IsZero(m.Past[i]) { // not required
			continue
		}

		if m.Past[i] != nil {
			if err := m.Past[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("past" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PlotData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PlotData) UnmarshalBinary(b []byte) error {
	var res PlotData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
